CREATE TABLE TB_BOARD ( NUM NUMBER(10) NOT NULL, NAME VARCHAR2(20) NOT NULL, TITLE VARCHAR2(100) NOT NULL, CONTENT CLOB NULL, READ_COUNT NUMBER(10) DEFAULT 0 NOT NULL, WRITE_DATE DATE NOT NULL ); ALTER TABLE TB_BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (NUM);

ALTER TABLE TB_BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (NUM);

select * from TB_BOARD;

INSERT INTO TB_BOARD VALUES (1, '홍길동','게시물 작성', '글 내용', 0, SYSDATE);

